language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
branches:
  only:
  - master
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: coverage
      script: npm run report-coverage
    - stage: release
      script: npm run semantic-release
