language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
branches:
  only:
  - master
script:
  - npm run test
after_success:
  - npm run report-coverage
  - npm run semantic-release
